import {beforeAll,afterAll,beforeEach,describe,it,expect} from 'vitest';
import {MongoMemoryReplSet} from 'mongodb-memory-server';
import {MongoClient} from 'mongodb';
import request from 'supertest';
import {initialize,col,type Store} from '../server/db';
import {selectSeats,startPayment,finalize,release,cleanup,snapshot} from '../server/booking';
import {createApp} from '../server/app';
import {askJarvis} from '../server/jarvis';
import {reconcile,validSignature} from '../server/payments';
import {createHmac} from 'node:crypto';
let repl:MongoMemoryReplSet,client:MongoClient,s:Store;
const tripId='test-trip';
beforeAll(async()=>{repl=await MongoMemoryReplSet.create({replSet:{count:1},binary:{version:'7.0.24'}});client=new MongoClient(repl.getUri(),{maxPoolSize:100});await client.connect();s={client,db:client.db('test'),holdMs:300000};await initialize(s);},180000);
afterAll(async()=>{await client?.close();await repl?.stop();});
beforeEach(async()=>{for(const name of ['users','trips','seats','holds','orders','payments','bookings','refunds','outbox','inbox','idempotency'])await col(s,name).deleteMany({});const departure=new Date(Date.now()+86400000);await col(s,'trips').insertOne({_id:tripId,from:'Bengaluru',to:'Chennai',date:departure.toISOString().slice(0,10),departureAt:departure,arrivalAt:new Date(departure.getTime()+6*3600000),fare:69900,status:'PUBLISHED',name:'Heaven Express',duration:6});await col(s,'seats').insertMany(['1A','1B','1C','1D'].map(seatId=>({_id:seatId,tripId,seatId,state:'AVAILABLE',version:0,holdId:null,expiresAt:null})));});
async function prepare(user='u1',seats=['1A']){const {hold}=await selectSeats(s,user,tripId,seats,`key-${user}`);await startPayment(s,user,hold._id,seats.map(()=>({name:'Test Passenger',age:24})),'9876543210','sandbox');return hold;}
async function forceExpiry(id:string){await col(s,'holds').updateOne({_id:id},{$set:{expiresAt:new Date(0)}});await col(s,'seats').updateMany({holdId:id},{$set:{expiresAt:new Date(0)}});}
describe('database-enforced booking safety',()=>{
 it('500 simultaneous claimants produce exactly one owner',async()=>{const results=await Promise.allSettled(Array.from({length:500},(_,i)=>selectSeats(s,`u${i}`,tripId,['1A'],`burst-${i}`)));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await col(s,'holds').countDocuments({active:true})).toBe(1);expect(await col(s,'seats').countDocuments({state:'HELD'})).toBe(1);},60000);
 it('rolls back a whole conflicting group',async()=>{await selectSeats(s,'u1',tripId,['1B'],'first-key');await expect(selectSeats(s,'u2',tripId,['1A','1B'],'second-key')).rejects.toThrow();expect((await col(s,'seats').findOne({seatId:'1A'}))!.state).toBe('AVAILABLE');});
 it('reclaims expired seats with the cleanup worker stopped',async()=>{const {hold}=await selectSeats(s,'u1',tripId,['1A'],'first-key');await forceExpiry(hold._id);const next=await selectSeats(s,'u2',tripId,['1A'],'second-key');expect(next.hold.userId).toBe('u2');await release(s,'u1',hold._id);expect((await col(s,'seats').findOne({seatId:'1A'}))!.holdId).toBe(next.hold._id);});
 it('keeps the original deadline and replays idempotent selection',async()=>{const first=await selectSeats(s,'u1',tripId,['1A'],'first-key');const replay=await selectSeats(s,'u1',tripId,['1A'],'first-key');expect(replay.hold._id).toBe(first.hold._id);const second=await selectSeats(s,'u1',tripId,['1A','1B'],'second-key');expect(second.hold.expiresAt).toEqual(first.hold.expiresAt);await expect(selectSeats(s,'u1',tripId,['1C'],'first-key')).rejects.toThrow('different selection');});
 it('deduplicates simultaneous payment confirmations',async()=>{const h=await prepare();const results=await Promise.all(Array.from({length:20},()=>finalize(s,h._id,'pay-one',h.amount,'INR')));expect(results.every(r=>r.status==='CONFIRMED')).toBe(true);expect(await col(s,'bookings').countDocuments()).toBe(1);expect(await col(s,'payments').countDocuments()).toBe(1);expect((await col(s,'seats').findOne({seatId:'1A'}))!.state).toBe('BOOKED');},30000);
 it('refunds a late payment without stealing the new hold',async()=>{const h=await prepare();await forceExpiry(h._id);const next=await selectSeats(s,'u2',tripId,['1A'],'new-owner');expect((await finalize(s,h._id,'pay-late',h.amount,'INR')).status).toBe('REFUND_PENDING');expect((await col(s,'seats').findOne({seatId:'1A'}))!.holdId).toBe(next.hold._id);await finalize(s,h._id,'pay-late',h.amount,'INR');expect(await col(s,'refunds').countDocuments()).toBe(1);await reconcile(s,{mode:'sandbox'});expect((await col(s,'refunds').findOne({_id:'pay-late'}))!.status).toBe('COMPLETED');});
 it('returns expired inventory as available before cleanup',async()=>{const {hold}=await selectSeats(s,'u1',tripId,['1A'],'first-key');await forceExpiry(hold._id);expect((await snapshot(s,tripId)).seats.find(x=>x.seatId==='1A')?.state).toBe('AVAILABLE');await cleanup(s);expect((await col(s,'holds').findOne({_id:hold._id}))!.active).toBe(false);});
 it('never partially confirms multiple seats',async()=>{const h=await prepare('u1',['1A','1B']);await col(s,'seats').updateOne({seatId:'1B'},{$set:{holdId:'other'}});const r=await finalize(s,h._id,'pay-group',h.amount,'INR');expect(r.status).toBe('REFUND_PENDING');expect(await col(s,'seats').countDocuments({state:'BOOKED'})).toBe(0);});
 it('rejects a changed payment amount',async()=>{const h=await prepare();await expect(finalize(s,h._id,'pay-bad',1,'INR')).rejects.toThrow('amount');expect(await col(s,'bookings').countDocuments()).toBe(0);});
 it('refunds a second distinct captured payment for the same booking',async()=>{const h=await prepare();await finalize(s,h._id,'pay-first',h.amount,'INR');expect((await finalize(s,h._id,'pay-second',h.amount,'INR')).status).toBe('REFUND_PENDING');expect(await col(s,'bookings').countDocuments()).toBe(1);expect((await col(s,'seats').findOne({seatId:'1A'}))!.state).toBe('BOOKED');});
 it('handles cleanup and finalization racing without duplicate allocation',async()=>{const h=await prepare();await Promise.allSettled([cleanup(s),finalize(s,h._id,'pay-race',h.amount,'INR'),selectSeats(s,'u2',tripId,['1A'],'race-other')]);expect(await col(s,'bookings').countDocuments()).toBe(1);expect((await col(s,'seats').findOne({seatId:'1A'}))!.state).toBe('BOOKED');});
});
describe('API and assistant',()=>{
 const cfg={secret:'test-only-secret-with-more-than-32-characters',origins:['http://localhost:5173'],payment:{mode:'sandbox'}};
 it('requires auth and protects admin access',async()=>{const app=createApp(()=>s,cfg);expect((await request(app).post('/api/holds').send({tripId,seatIds:['1A']})).status).toBe(401);const signup=await request(app).post('/api/auth/register').send({name:'Tester',email:'tester@example.test',password:'test-password-123'});expect(signup.status).toBe(200);expect((await request(app).get('/api/admin/overview').set('Authorization',`Bearer ${signup.body.token}`)).status).toBe(403);});
 it('does not accept a foreign reservation or forged webhook',async()=>{const h=await prepare();const app=createApp(()=>s,cfg);const u=await request(app).post('/api/auth/register').send({name:'Other',email:'other@example.test',password:'test-password-123'});expect((await request(app).get(`/api/holds/${h._id}`).set('Authorization',`Bearer ${u.body.token}`)).status).toBe(404);expect((await request(app).post('/api/webhooks/razorpay').send({event:'payment.captured'})).status).toBe(400);});
 it('validates webhook HMAC signatures without timing-unsafe comparison',()=>{const payload='{}',secret='secret';const sig=createHmac('sha256',secret).update(payload).digest('hex');expect(validSignature(payload,sig,secret)).toBe(true);expect(validSignature(payload,'invalid',secret)).toBe(false);});
 it('searches real inventory by conversational route and budget',async()=>{const date=(await col(s,'trips').findOne({_id:tripId}))!.date;const r=await askJarvis(s,`Bengaluru to Chennai on ${date} under 800`);expect(r.trips).toHaveLength(1);expect(r.trips![0]._id).toBe(tripId);const cheaper=await askJarvis(s,'under 500',r.context);expect(cheaper.trips).toHaveLength(0);});
 it('returns a truthful setup state without a database',async()=>{const app=createApp(()=>null,cfg);expect((await request(app).get('/api/health/live')).status).toBe(200);expect((await request(app).get('/api/health/ready')).status).toBe(503);expect((await request(app).get('/api/trips')).status).toBe(503);});
});
